# Generated by Django 5.0.6 on 2026-02-01 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён'), ('completed', 'Выполнен')], default='created', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
            ],
            options={
                'verbose_name': 'Передача инструмента',
                'verbose_name_plural': 'Передачи инструментов',
                'ordering': ['-created_at'],
            },
        ),
    ]
