# Generated by Django 5.0.6 on 2026-02-01 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '__first__'),
        ('tools', '0001_initial'),
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='foreman',
            field=models.ForeignKey(limit_choices_to={'role': 'foreman'}, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Бригадир, инициировавший запрос'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='objects.constructionobject', verbose_name='Объект-отправитель'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='objects.constructionobject', verbose_name='Объект-получатель'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='tools.tool', verbose_name='Инструмент'),
        ),
    ]
