# Generated by Django 6.0.4 on 2026-04-23 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=12, unique=True)),
                ('kpp', models.CharField(blank=True, max_length=9)),
                ('address', models.TextField(blank=True)),
                ('external_1c_id', models.CharField(blank=True, db_index=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneCExchangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('import', 'Импорт из 1С'), ('export', 'Экспорт в 1С')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка')], max_length=10)),
                ('payload', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('external_1c_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='inventory.legalentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('office', 'Офис'), ('building', 'Здание'), ('floor', 'Этаж'), ('room', 'Помещение')], max_length=20)),
                ('external_1c_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.legalentity')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.location')),
            ],
            options={
                'unique_together': {('legal_entity', 'name', 'type', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе'), ('completed', 'Завершена')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions', to='inventory.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('inventory_number', models.CharField(max_length=128, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Исправен'), ('damaged', 'Поврежден'), ('lost', 'Отсутствует'), ('written_off', 'Списан')], default='active', max_length=20)),
                ('qr_code', models.CharField(blank=True, db_index=True, max_length=128)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/photos/')),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_inventory_at', models.DateTimeField(blank=True, null=True)),
                ('external_1c_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory.assetcategory')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory.employee')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=20)),
                ('command_text', models.TextField(blank=True)),
                ('external_1c_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.asset')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.employee')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.location')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.employee')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WriteOffAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('wear_level_percent', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждено'), ('sent_to_1c', 'Отправлено в 1С')], default='draft', max_length=20)),
                ('external_1c_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_acts', to='inventory.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_acts', to='inventory.legalentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('detected', models.BooleanField(default=True)),
                ('detected_inventory_number', models.CharField(blank=True, max_length=128)),
                ('ocr_text', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('ok', 'Исправен'), ('damaged', 'Поврежден'), ('absent', 'Отсутствует')], default='ok', max_length=20)),
                ('ai_condition', models.CharField(blank=True, choices=[('ok', 'Исправен'), ('damaged', 'Поврежден'), ('absent', 'Отсутствует')], max_length=20)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_provider', models.CharField(blank=True, max_length=64)),
                ('ai_comment', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inventory/photos/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.asset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorysession')),
            ],
            options={
                'unique_together': {('session', 'asset')},
            },
        ),
    ]
