# Generated by Django 6.0.4 on 2026-04-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_asset_price_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysession',
            name='external_1c_id',
            field=models.CharField(blank=True, db_index=True, help_text='Идентификатор сессии в 1С (GUID/номер документа) для идемпотентного импорта.', max_length=128, null=True, unique=True),
        ),
    ]
