# Generated by Django 6.0.4 on 2026-04-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorysession_external_1c_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='inventory/assets-history/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_photos', to='inventory.asset')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_photos', to='inventory.inventoryitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_photos', to='inventory.inventorysession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
