# Generated by Django 5.0.6 on 2026-02-01 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название инструмента',
                'verbose_name_plural': 'Названия инструментов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('inventory_number', models.CharField(max_length=255, unique=True, verbose_name='Инвентарный номер')),
                ('qr_code', models.CharField(max_length=255, unique=True, verbose_name='QR-код')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tools/', verbose_name='Фото инструмента')),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('in_work', 'В работе'), ('transferred', 'Передан'), ('written_off', 'Списан')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('current_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='objects.constructionobject', verbose_name='Текущий объект')),
                ('tool_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='tools.toolname', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='ToolTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('transfer_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата перемещения')),
                ('from_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_transfers_from', to='objects.constructionobject', verbose_name='Объект-отправитель')),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_transfers_to', to='objects.constructionobject', verbose_name='Объект-получатель')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='tools.tool', verbose_name='Инструмент')),
            ],
            options={
                'verbose_name': 'История перемещения инструмента',
                'verbose_name_plural': 'История перемещений инструментов',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
