# Generated by Django 5.0.6 on 2026-02-01 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='Присутствует')),
            ],
            options={
                'verbose_name': 'Инструмент в инвентаризации',
                'verbose_name_plural': 'Инструменты в инвентаризациях',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='objects.constructionobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
                'ordering': ['-date'],
            },
        ),
    ]
