# Generated by Django 5.0.6 on 2026-02-01 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, проводивший инвентаризацию'),
        ),
        migrations.AddField(
            model_name='inventorytool',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_tools', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventorytool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_tools', to='tools.tool'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='tools',
            field=models.ManyToManyField(related_name='inventories', through='inventory.InventoryTool', to='tools.tool', verbose_name='Инструменты'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorytool',
            unique_together={('inventory', 'tool')},
        ),
    ]
